<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ProbyQuest!</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="css/index.css">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Begin page content -->
    <div class="container">
      <div class="page-header">
        <h1>ProbyQuest!</h1>
      </div>
      <p class="lead">
		<div class="container">
			Active Quests:
			<form>
			<ul>
			Be the fucking cutest!<br/>
			<div class="radio">
					<label><input type="radio" name="optradio">A+!</label>
			</div>
			<div class="radio">
					<label><input type="radio" name="optradio">B</label>
			</div>
			<div class="radio">
					<label><input type="radio" name="optradio">C</label>
			</div>
			<div class="radio">
					<label><input type="radio" name="optradio">...</label>
			</div>
			</ul>
			<button type="submit" class="btn btn-primary">
				<i class="icon-user icon-white"></i>Yeah, I rocked this!
			</button>
			</form>	
		</div>
	  </p>
		<div class="row container">
			<br/><br/>
			<div class="progress">
				<div class="progress-bar progress-bar-striped active" role="progressbar"
					style="width:90%">
				Probypoints: 40. Almost there!
				</div>
				<div class="progress-bar progress-bar-warning" role="progressbar"
					style="width:10%">
				</div>
			</div>
		</div>
    </div>
	<div class="container text-center" style="text-shadow:none">
		<ul class="pagination">
		  <li class="active"><a href="#">Active Quests</a></li>
		  <li><a href="#">Quest Reports</a></li>
		  <li><a href="#">Probyprizes</a></li>
		</ul>
	</div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">TechTheTech Studios. Last updated <?php echo date("d M Y"); ?></p>
      </div>
    </footer>
  </body>
</html>
